name: team_mobileforce_gong
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  sqflite: any
  path_provider: any
  cached_network_image: ^2.2.0+1
  intl:
  google_fonts:
  http:
  flutter_svg:
  device_preview:
  google_sign_in:
  flutter_signin_button:
  launch_review: ^2.0.0
  get: ^3.2.2
  data_connection_checker: ^0.3.4
  flappy_search_bar: 1.4.1
  uuid: ^2.2.0

  rate_my_app:
    path: ./rate_my_app
  
  
  flutter:
    sdk: flutter
  shared_preferences:
  provider:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  image_picker: ^0.6.7+2
  firebase_auth:
  cloud_firestore:
  local_auth: ^0.4.0+1
  share: 
  flutter_local_notifications:
  simple_animations:
  supercharged:
  url_launcher:
  firebase_storage:
  cached_network_image:
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:


flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/notes.png"
  image_path_ios: "assets/images/notes.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/images/

  fonts:
    - family: Shadows
      fonts:
        - asset: assets/fonts/ShadowsIntoLight-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/MontserratAlternates-Light.ttf
    - family: Cedarville
      fonts:
        - asset: assets/fonts/CedarvilleCursive-Regular.ttf
    - family: ComicNeue
      fonts:
       - asset: assets/fonts/ComicNeue-Regular.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.otf
        - asset: assets/fonts/Gilroy-Light.otf
        - asset: assets/fonts/Gilroy-medium.ttf
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 800


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
